# Generated by Django 4.2.2 on 2023-06-28 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ptu12_final/media/', verbose_name='picture')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('residence', models.CharField(db_index=True, max_length=50, verbose_name='residence')),
                ('programming_languages', models.TextField(max_length=4000, verbose_name='programming languages')),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True, verbose_name='hobbies')),
                ('email', models.CharField(db_index=True, max_length=100, verbose_name='email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+99999999999'. Up to 11 digits are allowed.", regex='^\\+370\\d{8}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_informations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'personal information',
                'verbose_name_plural': 'personal informations',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, max_length=4000, null=True, verbose_name='about me')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_scrape_send.personalinformation', verbose_name='personal information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_mes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'about me',
                'verbose_name_plural': 'about mes',
            },
        ),
    ]
