# Generated by Django 4.2.2 on 2023-06-30 05:21

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('create_scrape_send', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+370XXXXXXXX'. Up to 11 digits are allowed.", regex='^\\+370\\d{8}$')]),
        ),
    ]
