# Generated by Django 4.2.2 on 2023-07-03 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_scrape_send', '0002_alter_personalinformation_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='SendScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_scrape_send.aboutme', verbose_name='about me')),
                ('emails', models.ManyToManyField(to='create_scrape_send.email', verbose_name='emails')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_scrape_send.personalinformation', verbose_name='personal information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_scrapeds', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'send scraped',
                'verbose_name_plural': 'send scrapeds',
            },
        ),
    ]
